# Develop mode docker-compose file
services:
  app:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - GH_CLIENT_ID=${GH_CLIENT_ID}
      - GH_SECRET=${GH_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    command: bun dev
